# Generated by Django 3.2.7 on 2021-09-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myFiles',
            fields=[
                ('mid', models.IntegerField(primary_key=True, serialize=False)),
                ('cv', models.FileField(upload_to='uploads/')),
                ('project', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
