# Generated by Django 3.2.3 on 2021-09-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_myfiles_mid'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='university',
            field=models.CharField(default='', max_length=150),
        ),
    ]
